Repository Clansty/Icalingua, pull requests merged in 2021-08, with the labels that each got.

#140 添加群和好友数据导出功能
  icalingua/package.json
  icalingua/src/main/ipc/botAndStorage.ts
  icalingua/src/main/ipc/menuManager.ts
  icalingua/src/main/utils/exportContacts.ts
  icalingua/src/main/utils/writeCsvData.ts
  icalingua/yarn.lock
Labels: enhancement

#163 Feature/flashpic
  icalingua-bridge-oicq/utils/processMessage.ts
  icalingua/src/index.ejs
  icalingua/src/main/ipc/menuManager.ts
  icalingua/src/main/storageProviders/SQLStorageProvider.ts
  icalingua/src/main/storageProviders/SQLUpgradeScript/2to3.ts
  icalingua/src/main/utils/processMessage.ts
  icalingua/src/renderer/components/vac-mod/ChatWindow/Message/MessageImage.vue
  icalingua/src/renderer/components/vac-mod/ChatWindow/Room/Room.vue
  icalingua/src/types/Message.d.ts
  icalingua/static/lightning.svg
Labels: enhancement, official

#139 版本更新：2.2.0
  .github/workflows/main.yml
  .idea/codeStyles/Project.xml
  .idea/codeStyles/codeStyleConfig.xml
  README.md
  icalingua-bridge-oicq/.gitignore
  icalingua-bridge-oicq/adapters/oicqAdapter.ts
  icalingua-bridge-oicq/custom.example/index.ts
  icalingua-bridge-oicq/handlers/registerSocketHandlers.ts
  icalingua-bridge-oicq/package.json
  icalingua-bridge-oicq/providers/configManager.ts
  icalingua-bridge-oicq/utils/clients.ts
  icalingua-bridge-oicq/utils/getImageUrlByMd5.ts
  icalingua-bridge-oicq/utils/processMessage.ts
  icalingua-bridge-oicq/yarn.lock
  icalingua/.gitignore
  icalingua/.yarn/releases/yarn-berry.cjs
  icalingua/.yarnrc.yml
  icalingua/package.json
  icalingua/src/index.ejs
  icalingua/src/main/adapters/oicqAdapter.ts
  icalingua/src/main/adapters/socketIoAdapter.ts
  icalingua/src/main/ipc/botAndStorage.ts
  icalingua/src/main/ipc/menuManager.ts
  icalingua/src/main/ipc/openImage.ts
  icalingua/src/main/storageProviders/RedisStorageProvider.ts
  icalingua/src/main/storageProviders/SQLStorageProvider.ts
  icalingua/src/main/storageProviders/SQLUpgradeScript/2to3.ts
  icalingua/src/main/utils/errorHandler.ts
  icalingua/src/main/utils/exportContacts.ts
  icalingua/src/main/utils/exportGroupMembers.ts
  icalingua/src/main/utils/migrateData.ts
  icalingua/src/main/utils/openMedia.ts
  icalingua/src/main/utils/processMessage.ts
  icalingua/src/main/utils/ui.ts
  icalingua/src/main/utils/windowManager.ts
  icalingua/src/main/utils/writeCsvData.ts
  icalingua/src/renderer/components/TheContactsPanel.vue
  icalingua/src/renderer/components/vac-mod/ChatWindow/Message/Message.vue
  icalingua/src/renderer/components/vac-mod/ChatWindow/Message/MessageImage.vue
  icalingua/src/renderer/components/vac-mod/ChatWindow/Room/Room.vue
  icalingua/src/renderer/router/index.ts
  icalingua/src/renderer/utils/ipc.ts
  icalingua/src/renderer/views/FriendRequest.vue
  icalingua/src/renderer/views/GroupNickEdit.vue
  icalingua/src/renderer/views/IgnoreManageView.vue
  icalingua/src/types/Adapter.d.ts
  icalingua/src/types/Message.d.ts
  icalingua/src/utils/getImageUrlByMd5.ts
  icalingua/src/utils/getStaticPath.ts
  icalingua/static/imgView.html
  icalingua/static/lightning.svg
  icalingua/yarn.lock
Labels: official, update

#191 Theme
  icalingua/src/main/ipc/botAndStorage.ts
  icalingua/src/main/ipc/menuManager.ts
  icalingua/src/main/utils/configManager.ts
  icalingua/src/main/utils/themes.ts
  icalingua/src/renderer/utils/themes.ts
  icalingua/src/renderer/views/ChatView.vue
  icalingua/src/renderer/views/HistoryView.vue
Labels: enhancement

#195 bug fix #193
  icalingua/src/main/adapters/oicqAdapter.ts
Labels: bug
